# Setup
title:               Jingyu (Marcel) Lee 
tagline:             'Personal Blog & Portfolio'
description:         'Since 2021-04-11'
url:                 https://jingyumarcellee.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jingyu (Marcel) Lee
  url:               https://jingyumarcellee.github.io
  email:             leemar@dickinson.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-jingyumarcellee-github-io-1